use super::{Command, Resource};
use anyhow::{Result, ensure};

pub(super) fn validate(command: &Command, source: &Resource) -> Result<()> {
    let w = command.source_width as usize;
    let h = command.source_height as usize;
    ensure!(
        w > 0 && h > 0 && w <= 8192 && h <= 8192,
        "invalid sprite dimensions"
    );
    ensure!(
        command.source_x <= 7 && command.source_y == 0 && command.transparent == 256,
        "invalid sprite options"
    );
    let axis = 2 * w * h;
    ensure!(
        source.bytes.len() == axis + 8 * (w + h) + 256,
        "invalid sprite asset length"
    );
    for pixel in source.bytes[..axis].chunks_exact(2) {
        ensure!(pixel[1] <= 1, "invalid sprite coverage");
    }
    for (offset, count) in [(axis, w), (axis + 8 * w, h)] {
        let mut previous = None;
        for i in 0..count {
            let index = offset + 8 * i;
            let start = u32::from_le_bytes(source.bytes[index..index + 4].try_into().unwrap());
            let length = u32::from_le_bytes(source.bytes[index + 4..index + 8].try_into().unwrap());
            ensure!(
                start <= 16384 && length <= 16384 && start + length <= 16384,
                "invalid sprite scaling range"
            );
            ensure!(
                previous.is_none_or(|end| end == start),
                "noncontiguous sprite scaling ranges"
            );
            previous = Some(start + length);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::draw::{DrawRenderer, IMAGE, SPRITE};
    use std::io::Read;

    fn word(bytes: &[u8], index: usize) -> u32 {
        u32::from_le_bytes(bytes[index * 4..index * 4 + 4].try_into().unwrap())
    }

    #[test]
    fn rejects_malformed_sprite_assets() {
        let command = Command {
            kind: SPRITE,
            source_width: 1,
            source_height: 1,
            ..Default::default()
        };
        let mut resource = Resource {
            width: 1,
            height: 1,
            pitch: 1,
            bytes: vec![0; 274],
        };
        validate(&command, &resource).unwrap();
        resource.bytes[1] = 2;
        assert!(validate(&command, &resource).is_err());
        resource.bytes[1] = 1;
        resource.bytes[2..6].copy_from_slice(&u32::MAX.to_le_bytes());
        assert!(validate(&command, &resource).is_err());
        resource.bytes.clear();
        assert!(validate(&command, &resource).is_err());
        assert!(
            validate(
                &Command {
                    source_width: u32::MAX,
                    ..command
                },
                &resource
            )
            .is_err()
        );
    }

    #[test]
    #[ignore = "requires GPU and KFX_SPRITE_FIXTURE generated by sprite_fixture"]
    fn gpu_actual_legacy_sprites() {
        let path = std::env::var("KFX_SPRITE_FIXTURE").expect("set KFX_SPRITE_FIXTURE");
        let mut file = std::io::BufReader::new(std::fs::File::open(path).unwrap());
        let mut header = [0u8; 20];
        file.read_exact(&mut header).unwrap();
        assert_eq!(word(&header, 0), 0x3353464b);
        assert_eq!(word(&header, 4), 112);
        let count = word(&header, 1);
        let width = word(&header, 2);
        let height = word(&header, 3);
        let size = (width * height) as usize;
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle());
        let adapter = pollster::block_on(instance.request_adapter(&Default::default())).unwrap();
        eprintln!("sprite fixtures adapter: {:?}", adapter.get_info());
        let (device, queue) =
            pollster::block_on(adapter.request_device(&Default::default())).unwrap();
        let renderer = crate::gpu::Renderer::new(device, queue).unwrap();
        let mut drawing = DrawRenderer::new(&renderer, wgpu::TextureFormat::Rgba8Unorm).unwrap();
        let target = drawing.create_target(width, height).unwrap();
        let initial: Vec<u8> = (0..size)
            .map(|i| (i * 19 + i / width as usize * 13) as u8)
            .collect();
        let initial_source = drawing
            .create_resource(&initial, width, height, width)
            .unwrap();
        let mut expected = vec![0; size];
        for fixture in 0..count {
            let mut bytes = [0; 112];
            file.read_exact(&mut bytes).unwrap();
            let mut length = [0; 4];
            file.read_exact(&mut length).unwrap();
            let mut source = vec![0; u32::from_le_bytes(length) as usize];
            file.read_exact(&mut source).unwrap();
            let source_handle = drawing.create_resource(&source, 1, 1, 1).unwrap();
            source.fill(19);
            let mut table_handle = 0;
            if word(&bytes, 2) != 0 {
                let mut table = vec![0; 65536];
                file.read_exact(&mut table).unwrap();
                table_handle = drawing.create_resource(&table, 256, 256, 256).unwrap();
                table.fill(23);
            }
            file.read_exact(&mut expected).unwrap();
            let command = Command {
                abi_version: word(&bytes, 0),
                kind: word(&bytes, 1),
                blend: word(&bytes, 2),
                colour: word(&bytes, 3),
                x: word(&bytes, 4) as i32,
                y: word(&bytes, 5) as i32,
                width: word(&bytes, 6),
                height: word(&bytes, 7),
                clip_x: word(&bytes, 8) as i32,
                clip_y: word(&bytes, 9) as i32,
                clip_width: word(&bytes, 10),
                clip_height: word(&bytes, 11),
                source: source_handle,
                table: table_handle,
                source_x: word(&bytes, 16),
                source_y: word(&bytes, 17),
                source_width: word(&bytes, 18),
                source_height: word(&bytes, 19),
                start_low: word(&bytes, 20),
                start_high: word(&bytes, 21),
                step_low: word(&bytes, 22),
                step_high: word(&bytes, 23),
                transparent: word(&bytes, 24),
                ..Default::default()
            };
            drawing
                .submit(
                    target,
                    &[
                        Command {
                            kind: IMAGE,
                            source: initial_source,
                            width,
                            height,
                            source_width: width,
                            source_height: height,
                            ..Default::default()
                        },
                        command,
                    ],
                )
                .unwrap();
            drawing.release_resource(source_handle).unwrap();
            if table_handle != 0 {
                drawing.release_resource(table_handle).unwrap();
            }
            let actual = drawing.readback(target).unwrap();
            if let Some(pixel) = actual.iter().zip(&expected).position(|(a, b)| a != b) {
                panic!(
                    "fixture {fixture} {command:?}: pixel ({},{}) GPU={} legacy={}",
                    pixel % width as usize,
                    pixel / width as usize,
                    actual[pixel],
                    expected[pixel]
                );
            }
        }
        let mut trailing = [0];
        assert_eq!(file.read(&mut trailing).unwrap(), 0);
        eprintln!("{count} exact actual-legacy sprite GPU fixtures passed");
    }
}
