use anyhow::{Context, Result, ensure};
use keeperfx_frame_replay::gpoly::{GpolyPreparer, RowLayout, Triangle, Vertex, row_layout};
use wgpu::util::DeviceExt;

fn bytes(words: &[u32]) -> Vec<u8> {
    words.iter().flat_map(|word| word.to_le_bytes()).collect()
}

fn readback(device: &wgpu::Device, buffer: &wgpu::Buffer) -> Result<Vec<u32>> {
    let (tx, rx) = std::sync::mpsc::channel();
    buffer
        .slice(..)
        .map_async(wgpu::MapMode::Read, move |result| tx.send(result).unwrap());
    device.poll(wgpu::PollType::Wait {
        submission_index: None,
        timeout: None,
    })?;
    rx.recv()??;
    let range = buffer.slice(..).get_mapped_range()?;
    let words = range
        .as_chunks::<4>()
        .0
        .iter()
        .map(|bytes| u32::from_le_bytes(*bytes))
        .collect();
    drop(range);
    buffer.unmap();
    Ok(words)
}

#[test]
#[ignore = "requires a GPU and KFX_GPOLY_TRIANGLE_FIXTURE generated by tests/gpoly"]
fn native_triangles_match_gpu_setup_and_pixels() -> Result<()> {
    let fixture = std::fs::read(std::env::var("KFX_GPOLY_TRIANGLE_FIXTURE")?)?;
    let mut data = fixture.as_slice();
    ensure!(data.starts_with(b"KFXGTRI1"), "invalid triangle fixture");
    data = &data[8..];
    fn word(data: &mut &[u8]) -> u32 {
        let value = u32::from_le_bytes(data[..4].try_into().unwrap());
        *data = &data[4..];
        value
    }
    let width = word(&mut data);
    let height = word(&mut data);
    let pitch = word(&mut data);
    let count = word(&mut data);
    let assets: Vec<u32> = data[..7968 + 16384].iter().map(|&v| u32::from(v)).collect();
    data = &data[7968 + 16384..];
    let mut triangles = Vec::new();
    let mut expected_spans = Vec::new();
    let mut expected_pixels = Vec::new();
    for _ in 0..count {
        let vertices = std::array::from_fn(|_| {
            let x = word(&mut data) as i32;
            let y = word(&mut data) as i32;
            let mut attribute = || {
                let low = word(&mut data);
                let high = word(&mut data);
                (u64::from(low) | (u64::from(high) << 32)) as i64
            };
            Vertex {
                x,
                y,
                u: attribute(),
                v: attribute(),
                shade: attribute(),
            }
        });
        triangles.push(Triangle { vertices });
        expected_spans.extend((0..height * 8).map(|_| word(&mut data)));
        let size = (pitch * height) as usize;
        expected_pixels.extend(data[..size].iter().map(|&v| u32::from(v)));
        data = &data[size..];
    }
    ensure!(data.is_empty(), "trailing fixture bytes");
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle());
    let adapter = pollster::block_on(instance.request_adapter(&Default::default()))?;
    eprintln!("GPU triangle validation: {:?}", adapter.get_info());
    let (device, queue) = pollster::block_on(adapter.request_device(&Default::default()))?;
    let (limited_device, _limited_queue) =
        pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
            required_limits: wgpu::Limits {
                max_buffer_size: 1024,
                max_storage_buffer_binding_size: 512,
                max_compute_workgroups_per_dimension: 1,
                ..Default::default()
            },
            ..Default::default()
        }))?;
    let limited_preparer = GpolyPreparer::new(&limited_device);
    let mut limited_encoder = limited_device.create_command_encoder(&Default::default());
    let spacious = limited_device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: 1024,
        usage: wgpu::BufferUsages::STORAGE,
        mapped_at_creation: false,
    });
    for (count, rows, message) in [
        (1, 33, "allocation limit"),
        (11, 1, "allocation limit"),
        (1, 17, "storage limit"),
        (6, 1, "storage limit"),
        (65, 1, "dispatch"),
    ] {
        let limited_layout: Vec<_> = (0..count as u32)
            .map(|index| RowLayout {
                base: index * rows,
                y_lo: 0,
                rows,
                width,
                height: rows,
            })
            .collect();
        let error = limited_preparer
            .encode(
                &limited_device,
                &mut limited_encoder,
                &triangles[..count],
                &limited_layout,
                &spacious,
                None,
            )
            .err()
            .context("oversized triangle batch was accepted")?;
        ensure!(error.to_string().contains(message), "{error}");
    }
    let preparer = GpolyPreparer::new(&device);
    let mut encoder = device.create_command_encoder(&Default::default());
    let extents = vec![(width, height); triangles.len()];
    let (layout, total_rows) = row_layout(&triangles, &extents);
    let arena = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: u64::from(total_rows) * 32,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: false,
    });
    assert!(
        preparer
            .encode(&device, &mut encoder, &[], &[], &arena, None)
            .is_err()
    );
    let wide = vec![(32768, height); triangles.len()];
    let (wide_layout, _) = row_layout(&triangles, &wide);
    assert!(
        preparer
            .encode(
                &device,
                &mut encoder,
                &triangles,
                &wide_layout,
                &arena,
                None
            )
            .is_err()
    );
    let mut unsupported = triangles[0];
    unsupported.vertices[0].x = 32768;
    assert!(
        preparer
            .encode(
                &device,
                &mut encoder,
                &[unsupported],
                &layout[..1],
                &arena,
                None
            )
            .is_err()
    );
    preparer.encode(&device, &mut encoder, &triangles, &layout, &arena, None)?;
    let rows_readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: arena.size(),
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    encoder.copy_buffer_to_buffer(&arena, 0, &rows_readback, 0, arena.size());
    queue.submit([encoder.finish()]);
    let compressed = readback(&device, &rows_readback).context("read GPU triangle setup")?;
    // The arena is read exactly the way the raster kernel addresses it, and every row the
    // native oracle produced outside a triangle's layout extent must be empty, so a layout
    // that is not a superset of what the setup kernel writes fails here rather than
    // silently dropping pixels.
    let mut actual_spans = vec![0u32; expected_spans.len()];
    let mut outside = 0;
    for (triangle, entry) in layout.iter().enumerate() {
        let rows = (triangle * height as usize * 8)..((triangle + 1) * height as usize * 8);
        for y in 0..height as usize {
            let expected = &expected_spans[rows.start + y * 8..rows.start + y * 8 + 8];
            if y < entry.y_lo as usize || y >= (entry.y_lo + entry.rows) as usize {
                outside += usize::from(expected.iter().any(|word| *word != 0));
                continue;
            }
            let at = (entry.base as usize + y - entry.y_lo as usize) * 8;
            actual_spans[rows.start + y * 8..rows.start + y * 8 + 8]
                .copy_from_slice(&compressed[at..at + 8]);
        }
    }
    ensure!(
        outside == 0,
        "{outside} native rows fall outside the layout extent"
    );
    let mut mismatches = 0;
    for (i, (actual, expected)) in actual_spans.iter().zip(&expected_spans).enumerate() {
        if actual != expected {
            if mismatches < 10 {
                eprintln!(
                    "span mismatch triangle={} row={} word={} actual={actual:08x} expected={expected:08x}",
                    i / (height as usize * 8),
                    i / 8 % height as usize,
                    i % 8
                );
            }
            mismatches += 1;
        }
    }
    ensure!(mismatches == 0, "{mismatches} GPU setup word mismatches");
    let mut encoder = device.create_command_encoder(&Default::default());
    let spans = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: &bytes(&actual_spans),
        usage: wgpu::BufferUsages::STORAGE,
    });
    let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("gpoly fixture pixels"),
        source: wgpu::ShaderSource::Wgsl(include_str!("gpoly_pixels.wgsl").into()),
    });
    let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
        label: None,
        layout: None,
        module: &shader,
        entry_point: Some("render"),
        compilation_options: Default::default(),
        cache: None,
    });
    let asset_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: &bytes(&assets),
        usage: wgpu::BufferUsages::STORAGE,
    });
    let params = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: &bytes(&[width, height, count, pitch]),
        usage: wgpu::BufferUsages::UNIFORM,
    });
    let pixels = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: u64::from(pitch) * u64::from(height) * u64::from(count) * 4,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: false,
    });
    let pixels_readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: pixels.size(),
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let binding = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: None,
        layout: &pipeline.get_bind_group_layout(0),
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: spans.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: asset_buffer.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: pixels.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: params.as_entire_binding(),
            },
        ],
    });
    {
        let mut pass = encoder.begin_compute_pass(&Default::default());
        pass.set_pipeline(&pipeline);
        pass.set_bind_group(0, &binding, &[]);
        pass.dispatch_workgroups(pitch.div_ceil(8), height.div_ceil(8), count);
    }
    encoder.copy_buffer_to_buffer(&pixels, 0, &pixels_readback, 0, pixels.size());
    queue.submit([encoder.finish()]);
    let actual_pixels = readback(&device, &pixels_readback).context("read GPU triangle pixels")?;
    assert_eq!(actual_pixels.len(), expected_pixels.len());
    for (i, (actual, expected)) in actual_pixels.iter().zip(&expected_pixels).enumerate() {
        ensure!(
            actual == expected,
            "pixel mismatch triangle={} x={} y={} actual={actual} expected={expected}",
            i / (pitch * height) as usize,
            i % pitch as usize,
            i / pitch as usize % height as usize
        );
    }
    eprintln!(
        "PASS: {count} original-vertex triangles, {} exact setup words, {} exact palette indices including pitch padding",
        expected_spans.len(),
        expected_pixels.len()
    );
    Ok(())
}
