use anyhow::{Context, Result, ensure};
use keeperfx_frame_replay::gpoly::{GpolyPreparer, Triangle, Vertex};
use wgpu::util::DeviceExt;

fn bytes(words: &[u32]) -> Vec<u8> {
    words.iter().flat_map(|word| word.to_le_bytes()).collect()
}

fn readback(device: &wgpu::Device, buffer: &wgpu::Buffer) -> Result<Vec<u32>> {
    let (tx, rx) = std::sync::mpsc::channel();
    buffer
        .slice(..)
        .map_async(wgpu::MapMode::Read, move |result| tx.send(result).unwrap());
    device.poll(wgpu::PollType::Wait {
        submission_index: None,
        timeout: None,
    })?;
    rx.recv()??;
    let range = buffer.slice(..).get_mapped_range()?;
    let words = range
        .chunks_exact(4)
        .map(|bytes| u32::from_le_bytes(bytes.try_into().unwrap()))
        .collect();
    drop(range);
    buffer.unmap();
    Ok(words)
}

#[test]
#[ignore = "requires a GPU and KFX_GPOLY_TRIANGLE_FIXTURE generated by tests/gpoly"]
fn native_triangles_match_gpu_setup_and_pixels() -> Result<()> {
    let fixture = std::fs::read(std::env::var("KFX_GPOLY_TRIANGLE_FIXTURE")?)?;
    let mut data = fixture.as_slice();
    ensure!(data.starts_with(b"KFXGTRI1"), "invalid triangle fixture");
    data = &data[8..];
    fn word(data: &mut &[u8]) -> u32 {
        let value = u32::from_le_bytes(data[..4].try_into().unwrap());
        *data = &data[4..];
        value
    }
    let width = word(&mut data);
    let height = word(&mut data);
    let pitch = word(&mut data);
    let count = word(&mut data);
    let assets: Vec<u32> = data[..7968 + 16384].iter().map(|&v| u32::from(v)).collect();
    data = &data[7968 + 16384..];
    let mut triangles = Vec::new();
    let mut expected_spans = Vec::new();
    let mut expected_pixels = Vec::new();
    for _ in 0..count {
        let vertices = std::array::from_fn(|_| {
            let x = word(&mut data) as i32;
            let y = word(&mut data) as i32;
            let mut attribute = || {
                let low = word(&mut data);
                let high = word(&mut data);
                (u64::from(low) | (u64::from(high) << 32)) as i64
            };
            Vertex {
                x,
                y,
                u: attribute(),
                v: attribute(),
                shade: attribute(),
            }
        });
        triangles.push(Triangle { vertices });
        expected_spans.extend((0..height * 8).map(|_| word(&mut data)));
        let size = (pitch * height) as usize;
        expected_pixels.extend(data[..size].iter().map(|&v| u32::from(v)));
        data = &data[size..];
    }
    ensure!(data.is_empty(), "trailing fixture bytes");
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle());
    let adapter = pollster::block_on(instance.request_adapter(&Default::default()))?;
    eprintln!("GPU triangle validation: {:?}", adapter.get_info());
    let (device, queue) = pollster::block_on(adapter.request_device(&Default::default()))?;
    let preparer = GpolyPreparer::new(&device);
    let mut encoder = device.create_command_encoder(&Default::default());
    assert!(
        preparer
            .encode(&device, &mut encoder, &[], width, height)
            .is_err()
    );
    assert!(
        preparer
            .encode(&device, &mut encoder, &triangles, 32768, height)
            .is_err()
    );
    let mut unsupported = triangles[0];
    unsupported.vertices[0].x = 32768;
    assert!(
        preparer
            .encode(&device, &mut encoder, &[unsupported], width, height)
            .is_err()
    );
    let prepared = preparer.encode(&device, &mut encoder, &triangles, width, height)?;
    assert_eq!(
        (prepared.width, prepared.height, prepared.triangle_count),
        (width, height, count)
    );
    let rows_readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: prepared.rows.size(),
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    encoder.copy_buffer_to_buffer(&prepared.rows, 0, &rows_readback, 0, prepared.rows.size());
    let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("gpoly fixture pixels"),
        source: wgpu::ShaderSource::Wgsl(include_str!("gpoly_pixels.wgsl").into()),
    });
    let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
        label: None,
        layout: None,
        module: &shader,
        entry_point: Some("render"),
        compilation_options: Default::default(),
        cache: None,
    });
    let asset_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: &bytes(&assets),
        usage: wgpu::BufferUsages::STORAGE,
    });
    let params = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: &bytes(&[width, height, count, pitch]),
        usage: wgpu::BufferUsages::UNIFORM,
    });
    let pixels = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: u64::from(pitch) * u64::from(height) * u64::from(count) * 4,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: false,
    });
    let pixels_readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: pixels.size(),
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let binding = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: None,
        layout: &pipeline.get_bind_group_layout(0),
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: prepared.rows.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: asset_buffer.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: pixels.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: params.as_entire_binding(),
            },
        ],
    });
    {
        let mut pass = encoder.begin_compute_pass(&Default::default());
        pass.set_pipeline(&pipeline);
        pass.set_bind_group(0, &binding, &[]);
        pass.dispatch_workgroups(pitch.div_ceil(8), height.div_ceil(8), count);
    }
    encoder.copy_buffer_to_buffer(&pixels, 0, &pixels_readback, 0, pixels.size());
    queue.submit([encoder.finish()]);
    let actual_spans = readback(&device, &rows_readback).context("read GPU triangle setup")?;
    let mut mismatches = 0;
    for (i, (actual, expected)) in actual_spans.iter().zip(&expected_spans).enumerate() {
        if actual != expected {
            if mismatches < 10 {
                eprintln!(
                    "span mismatch triangle={} row={} word={} actual={actual:08x} expected={expected:08x}",
                    i / (height as usize * 8),
                    i / 8 % height as usize,
                    i % 8
                );
            }
            mismatches += 1;
        }
    }
    ensure!(mismatches == 0, "{mismatches} GPU setup word mismatches");
    let actual_pixels = readback(&device, &pixels_readback).context("read GPU triangle pixels")?;
    for (i, (actual, expected)) in actual_pixels.iter().zip(&expected_pixels).enumerate() {
        ensure!(
            actual == expected,
            "pixel mismatch triangle={} x={} y={} actual={actual} expected={expected}",
            i / (pitch * height) as usize,
            i % pitch as usize,
            i / pitch as usize % height as usize
        );
    }
    eprintln!(
        "PASS: {count} original-vertex triangles, {} exact setup words, {} exact palette indices including pitch padding",
        expected_spans.len(),
        expected_pixels.len()
    );
    Ok(())
}
